// お題。kanji は表示用、kana は判定用（ひらがな）。
export const WORDS = [
  // --- 技名系 ---
  { kanji: '波動拳', kana: 'はどうけん' },
  { kanji: '昇龍拳', kana: 'しょうりゅうけん' },
  { kanji: '竜巻旋風脚', kana: 'たつまきせんぷうきゃく' },
  { kanji: '瞬獄殺', kana: 'しゅんごくさつ' },
  { kanji: '真空波動拳', kana: 'しんくうはどうけん' },
  { kanji: '滅殺豪波動', kana: 'めっさつごうはどう' },
  { kanji: '疾風迅雷', kana: 'しっぷうじんらい' },
  { kanji: '電光石火', kana: 'でんこうせっか' },
  { kanji: '一撃必殺', kana: 'いちげきひっさつ' },
  { kanji: '天翔十字鳳', kana: 'てんしょうじゅうじほう' },
  { kanji: '百裂脚', kana: 'ひゃくれつきゃく' },
  { kanji: '覇王翔吼拳', kana: 'はおうしょうこうけん' },
  { kanji: '鳳凰脚', kana: 'ほうおうきゃく' },
  { kanji: '神龍拳', kana: 'しんりゅうけん' },
  { kanji: '灼熱波動拳', kana: 'しゃくねつはどうけん' },
  { kanji: '阿修羅閃空', kana: 'あしゅらせんくう' },
  { kanji: '空破弾', kana: 'くうはだん' },
  { kanji: '気功拳', kana: 'きこうけん' },
  { kanji: '双掌破', kana: 'そうしょうは' },
  { kanji: '螺旋岩砕', kana: 'らせんがんさい' },
  { kanji: '雷撃', kana: 'らいげき' },
  { kanji: '剛拳', kana: 'ごうけん' },
  { kanji: '無双正拳突き', kana: 'むそうせいけんづき' },
  { kanji: '大蛇薙', kana: 'おろちなぎ' },
  { kanji: '超必殺技', kana: 'ちょうひっさつわざ' },
  { kanji: '起死回生', kana: 'きしかいせい' },
  { kanji: '乾坤一擲', kana: 'けんこんいってき' },
  { kanji: '電撃波', kana: 'でんげきは' },
  { kanji: '奈落殺', kana: 'ならくざん' },
  { kanji: '烈風拳', kana: 'れっぷうけん' },

  // --- 格ゲー用語系 ---
  { kanji: '確定反撃', kana: 'かくていはんげき' },
  { kanji: '目押し', kana: 'めおし' },
  { kanji: '暴れ潰し', kana: 'あばれつぶし' },
  { kanji: '起き攻め', kana: 'おきぜめ' },
  { kanji: '差し返し', kana: 'さしかえし' },
  { kanji: '投げ抜け', kana: 'なげぬけ' },
  { kanji: '立ち回り', kana: 'たちまわり' },
  { kanji: '対空', kana: 'たいくう' },
  { kanji: '中段択', kana: 'ちゅうだんたく' },
  { kanji: '削り殺し', kana: 'けずりごろし' },
  { kanji: '相殺', kana: 'そうさい' },
  { kanji: '画面端', kana: 'がめんぎわ' },
  { kanji: '無敵技', kana: 'むてきわざ' },
  { kanji: '弾抜け', kana: 'たまぬけ' },
  { kanji: '屈伸', kana: 'くっしん' },
  { kanji: '判定勝ち', kana: 'はんていがち' },
  { kanji: '先読み', kana: 'さきよみ' },
  { kanji: '咄嗟の対応', kana: 'とっさのたいおう' },
  { kanji: '連続技', kana: 'れんぞくわざ' },
  { kanji: '開幕', kana: 'かいまく' },
  { kanji: '択を通す', kana: 'たくをとおす' },
  { kanji: '反応速度', kana: 'はんのうそくど' },
  { kanji: '割り込み', kana: 'わりこみ' },
  { kanji: '詐欺跳び', kana: 'さぎとび' },
  { kanji: '固め', kana: 'かため' },
  { kanji: '密着', kana: 'みっちゃく' },
  { kanji: '距離感', kana: 'きょりかん' },
  { kanji: '読み合い', kana: 'よみあい' },
  { kanji: '逆択', kana: 'ぎゃくたく' },
  { kanji: '最大反撃', kana: 'さいだいはんげき' },
  { kanji: '硬直', kana: 'こうちょく' },
  { kanji: '発生', kana: 'はっせい' },
  { kanji: '持続', kana: 'じぞく' },
  { kanji: '暴発', kana: 'ぼうはつ' },
  { kanji: '空振り', kana: 'からぶり' },
  { kanji: '差し込み', kana: 'さしこみ' },
  { kanji: '仕込み', kana: 'しこみ' },
  { kanji: '牽制', kana: 'けんせい' },

  // --- 実況セリフ系 ---
  { kanji: 'そこだ', kana: 'そこだ' },
  { kanji: '遅い', kana: 'おそい' },
  { kanji: '甘い', kana: 'あまい' },
  { kanji: '隙あり', kana: 'すきあり' },
  { kanji: '終わりだ', kana: 'おわりだ' },
  { kanji: '圧倒的', kana: 'あっとうてき' },
  { kanji: '覚悟しろ', kana: 'かくごしろ' },
  { kanji: '押し切る', kana: 'おしきる' },
  { kanji: '決めるぞ', kana: 'きめるぞ' },
  { kanji: '反撃開始', kana: 'はんげきかいし' },
  { kanji: '逃げ場はない', kana: 'にげばはない' },
  { kanji: '二度は効かん', kana: 'にどはきかん' },
  { kanji: '見えているぞ', kana: 'みえているぞ' },
  { kanji: '全弾命中', kana: 'ぜんだんめいちゅう' },
  { kanji: '気迫が違う', kana: 'きはくがちがう' },
  { kanji: '効いてないぞ', kana: 'きいてないぞ' },
  { kanji: '一撃でいい', kana: 'いちげきでいい' },
  { kanji: '燃え尽きろ', kana: 'もえつきろ' },
  { kanji: '一歩も引かん', kana: 'いっぽもひかん' },
  { kanji: '立ち上がれ', kana: 'たちあがれ' },
  { kanji: 'まだ終わらんよ', kana: 'まだおわらんよ' },
  { kanji: '完全に読み切った', kana: 'かんぜんによみきった' },
  { kanji: 'お前はもう終わりだ', kana: 'おまえはもうおわりだ' },
  { kanji: '勝負はここからだ', kana: 'しょうぶはここからだ' },
  { kanji: '全て見切った', kana: 'すべてみきった' },
  { kanji: '手加減はしない', kana: 'てかげんはしない' },
  { kanji: '力の差を見せてやる', kana: 'ちからのさをみせてやる' },
  { kanji: 'ここで決める', kana: 'ここできめる' },
  { kanji: '避けられんぞ', kana: 'さけられんぞ' },
  { kanji: '真の実力を見せろ', kana: 'しんのじつりょくをみせろ' },
];

// コンボが伸びるほど長いお題を出す
export const TIERS = [
  WORDS.filter((w) => w.kana.length <= 6),
  WORDS.filter((w) => w.kana.length >= 6 && w.kana.length <= 9),
  WORDS.filter((w) => w.kana.length >= 9),
];

export function pickWord(combo, avoid) {
  const pool = TIERS[combo >= 8 ? 2 : combo >= 4 ? 1 : 0];
  for (let n = 0; n < 8; n += 1) {
    const w = pool[Math.floor(Math.random() * pool.length)];
    if (w.kana !== avoid) return w;
  }
  return pool[0];
}
